### ISSUE TITLE
Скачок body при открытии модального окна

### ISSUE THREAD

**Issue by sharaputo** [AddMoreScripts/hystModal#10]
Здравствуйте. Отловил баг. При открытии модального окна на windows 10 (chrome, firefox) происходит скачок body на ширину скроллбара. На маках такого поведения нет, скрипт отрабатывает как и задумывалось.

**Comment by AddMoreScripts** [comment]
Добрый день. Подскажите, а есть ли он-лайн пример или репозиторий, чтобы посмотреть почему баг проявляется? 
Вообще, отступ справа вместо скроллбара вешается автоматически на тег html. Появляется ли margin-right: XXpx на html когда окно открывается? Или возможно висят ли какие-то специфические CSS-свойства на html или на body?

**Comment by sharaputo** [comment]
Добрый день. Вот репо https://sharaputo.github.io/AIFC/ <https://sharaputo.github.io/AIFC/>, там в секции Business где плитки, при нажатии на любую плитку появляется попап и на маке скроллбар учитывается, а на виндоус нет. На html и на body ничего нет, кроме базовых стилей шрифта и цвета текста.

**Comment by sharaputo** [comment]
Margin-right на html не появляется

**Comment by AddMoreScripts** [comment]
Да, вижу. У вас на html в базовых стилях висит width:100%;. Это не даёт поработать свойству margin-right. Имеет смысл поставить width:auto (или поставить width:100% только на body, а не на html).
В этом случае сдвига не будет. Так же, если вы используете последнюю версию hystmodal, то чтобы ещё и избежать сдвига фиксированного хеадера, добавьте ему аттрибут "data-hystfixed" (или другой, см. настройки). Только придётся тоже заменить в .header свойство width:100% на right:0; (чтобы было left:0; right:0;).
![Снимок экрана 2021-05-13 145535](https://user-images.githubusercontent.com/52598143/118116996-0dd31580-b3fc-11eb-834c-5a3d4dbc1cb8.jpg)

**Comment by sharaputo** [comment]
Спасибо. В сбросе стилей это прописано было, а я и не посмотрел!
