### ISSUE TITLE
Мусор в консоли

### ISSUE THREAD

**Issue by yuumatov** [AddMoreScripts/hystModal#13]
Пример: Если открыть модальное окно в котором есть форма с полями, при переключении фокуса табом в консоль выводятся цифры (как я понял порядковые номера фокусируемых элементов).
Вопрос: Зачем это нужно? Можно убрать?

**Comment by AddMoreScripts** [comment]
Да, действительно, там лишний вывод в консоль. Принял ваш pull-request.

**Comment by AddMoreScripts** [comment]
В новой версии, внесены v0.5 правки + убран мусор из консоли
