### ISSUE TITLE
Использование библиотеки с scroll-behavior: smooth;

### ISSUE THREAD

**Issue by dimau** [AddMoreScripts/hystModal#18]
Прежде всего, спасибо за библиотеку!

У меня на лендинге у html тега указано свойство "scroll-behavior: smooth;" чтобы плавно прокручивать при переходе по ссылкам из меню. Проблема возникает при закрытии модального окна - страница плавно проматывается к месту, на котором модальное окно было открыто. И это конечно недопустимо с точки зрения пользовательского опыта. Как этого можно избежать при использовании библиотеки?

**Comment by dimau** [comment]
Решил следующим образом

_bodyScrollControl() {
  ...
    if (this.isOpened === true) {
      html.classList.remove("modal__opened");
      html.style.marginRight = "";

      // Добавлено
      html.style.scrollBehavior = "auto";

      window.scrollTo(0, this._scrollPosition);

     // Добавлено
      html.style.scrollBehavior = "smooth";
       ...
    }

**Comment by AddMoreScripts** [comment]
Да, действительно есть такая проблема. Сама необходимость делать fixed + прокрутку возникла из-за совместимости с IE и одним багом в Safari в теперь уже неактуальной версии.
Думаю, в будущем, блокировка прокрутки может быть упрощена.
Решение в принципе, подходит. Ещё как вариант, можно менять html.style.scrollBehavior в коллбеках - `beforeOpen` и `afterClose`, тоже вроде бы должно работать, хотя не проверял.

**Comment by dimau** [comment]
Спасибо за подсказку, работает с коллбеками - beforeOpen и afterClose, и это более "красивый" способ
Подскажи, пожалуйста, насколько этот компонент на текущий момент актуальный? Я имею в виду, возможны, ты пользуешься уже чем-то другим для реализации модальных окон на сайтах? Или hystmodal?

**Comment by AddMoreScripts** [comment]
@dimau 
Сейчас да, актуальный. Пользуюсь им, особых проблем нет, ещё в документацию всё никак не добавил, что если есть сборщик - то подключать удобно из NPM https://www.npmjs.com/package/hystmodal 
Хочется заняться обновлениями (переписать с типизацией на TypeScript, добавить всё-таки какой-то функционал для показа одного окна над другим, убрать стилизацию крестика, и ещё некоторые улучшения, а так-же возможно отказаться от поддержки старых браузеров упростив код, и др. улучшения).
Пока, жду как немного времени освободится от основной работы.
