### ISSUE TITLE
Не работает catchFocus

### ISSUE THREAD

**Issue by IIIu6ko** [AddMoreScripts/hystModal#26]
Версия 1.0.1 не отрабатывает параметр catchFocus
Выставляю false, но после открытия фокус всё равно прыгает на инпут внутри модалки или на крестик для закрытия

**Comment by AddMoreScripts** [comment]
@IIIu6ko 
Добрый день.
Сейчас к сожалению нельзя отключить перенос фокуса на первый фокусируемый элемент внутри окна при открытии.
catchFocus - нужен для того чтобы переход по клавише `tab` или `ctrl+tab` зацикливал фокус внутри окна, пока оно открыто и не уходил с него, а когда окно закрывается - возвращал фокус на ссылку открытия (если она есть).

Вы можете поставить в начале кода модального окна какую-то кнопку скрытую которая может поймать фокус. Если она первая - по коду - то на неё будет фокус. А при закрытии - он будет возвращаться назад на элемент с которого окно открыли за счёт `catchFocus: true`
