### ISSUE TITLE
Add EditorConfig and Browserlist files

### ISSUE THREAD

**Issue by pepelsbey** [AddMoreScripts/hystModal#3]
1. [EditorConfig](https://editorconfig.org/) will give contributors the idea what editing rules should they use when proposing changes. Two spaces in package.json, 4 spaces in JS files? Sure. You can write it down in .editorconfig and editors will switch and give you the correct indentation in every case.
2. [Browserslist](https://github.com/browserslist/browserslist) could help stating the browser support you’re aiming for. Also automated tools will pick it up and use instead of built-in defaults.

**Comment by AddMoreScripts** [comment]
Yes, I plan to add EditorConfig in the new version as well. Browserslist also needs some work.

**Comment by AddMoreScripts** [comment]
EditorConfig is added in v0.4, Browserslist also added in package.json
