### ISSUE TITLE
Не смог подцепить через import

### ISSUE THREAD

**Issue by IIIu6ko** [AddMoreScripts/hystModal#5]
Webpack ругается
![изображение](https://user-images.githubusercontent.com/20703084/94436975-d03fb600-01a5-11eb-98bf-66d5e4f9c899.png)
Плюс
![изображение](https://user-images.githubusercontent.com/20703084/94437308-3c221e80-01a6-11eb-8f8d-92be2ebbcf83.png)
`import HystModal from 'hystmodal';`

**Comment by AddMoreScripts** [comment]
Добрый день. Вы подключили hystmodal через [npm](https://www.npmjs.com/package/hystmodal)?
К сожалению, ветка с версией для npm пока ещё недоделана, поэтому я не добавил npm в документацию.

Дело в том, что в hystmodal используются статические свойства классов и должны конвертироваться через babel (@babel/plugin-proposal-class-properties), но часто в webpack.config.js стоит исключение использования babel-loader для всей папки node_modules (правило exclude). В будущем я сконвертирую скрипт предварительно.

Пока вы можете просто подключить готовый файл
`import './node_modules/hystmodal/dist/hystmodal.min';`
он сразу добавит класс HystModal в глобальную область видимости и можно будет создать экземпляр.
`let myModal = new HystModal();`

Но я пока не советовал бы этого делать, так как структура файлов в npm в будущих версиях может измениться. Лучше просто подключить js-файлом.

**Comment by IIIu6ko** [comment]
@AddMoreScripts Я так и сделал. Правда eslint пришлось офнуть в файле с попапами.
