### ISSUE TITLE
Заполнения пробела для fixed элементов

### ISSUE THREAD

**Issue by IIIu6ko** [AddMoreScripts/hystModal#6]
Видео https://yadi.sk/i/LZ_y65dQQHliKw

Это реализовано в [scroll-lock](https://github.com/FL3NKEY/scroll-lock/blob/master/README.RU.md#%D0%B7%D0%B0%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%B5%D0%BB%D0%B0)

**Comment by AddMoreScripts** [comment]
Да, я планирую встроить подобный функционал в библиотеку, в ближайшее время, чтобы можно было указать css-класс, и к 
 элементам с этим классом при открытии окна добавлялся отступ.

**Comment by AddMoreScripts** [comment]
Добавлено новое свойство конфигурации - "fixedSelectors".
Там можно указать css-селектор, к которому добавляется отступ (margin-right) равный ширине полосы прокрутки, при открытии модального окна.
Даже если у элемента будет свой margin-right, скрипт его учтет.
По умолчанию это "*[data-hystfixed]", можно установить как css-класс, так и data-атрибут.
